---
title: "Presentations"
---

## Talks

### 2025

-   “**Potentially heritable biomarkers of neurodegeneration in a marmoset model of Alzheimer’s disease"**

    [*IEEE Women in Bioinformatics Workshop (WIBI) 2025, New Haven, CT, USA*]{.accent}

    **Sonal Kumar**, Catrina Spruce, Annat Haber, Laura Schultz, Hasi Huhe, Takeshi Murai, Sang-Ho Choi, Stephanie Hachem, Yongshan Mou, Seung-Kwon Ha, Jung Eun Park, Lauren Bailey, Lauren Mongeau, Andrew DeSana, Brianne Stein, Lauren K Hayrynen Schaeffer, Gregg E Homanics, Afonso C Silva, Stacey J Sukoff Rizzo, Gregory W Carter *\[February 2025\]*

    <a href="https://ieeexplore.ieee.org/document/11115210" class="btn btn-outline-primary">Abstract</a>
    
## Posters

### 2026

-   “**Genetic associations with plasma biomarkers measuring neurodegeneration in a population of laboratory marmosets"**

    [*Maine Chapter for the Society for Neuroscience, Bar Harbor, ME, USA*]{.accent}

    **Sonal Kumar**, Catrina Spruce, Annat Haber, Laura Schultz, Hasi Huhe, Takeshi Murai, Sang-Ho Choi, Stephanie Hachem, Yongshan Mou, Seung-Kwon Ha, Jung Eun Park, Lauren Bailey, Lauren Mongeau, Andrew DeSana, Brianne Stein, Lauren K Hayrynen Schaeffer, Gregg E Homanics, Afonso C Silva, Stacey J Sukoff Rizzo, Gregory W Carter *\[March 2026\]*

### 2025

-   **"Genetic associations with plasma biomarkers measuring neurodegeneration in a population of laboratory marmosets"**

    [*The 2025 Joint JAX Scientific Symposium and Faculty Retreat in Bar Harbor, ME, USA*]{.accent}

    **Sonal Kumar**, Annat Haber, Catrina Spruce, MARMO-AD Consortium, Diego Szczupak, Gregg Homanics, Afonso Silva, Stacey J. Sukoff Rizzo, Gregory W. Carter *\[October 2025\]*

-   **"Genetic associations with plasma biomarkers measuring neurodegeneration in a population of laboratory marmosets"**

    [*The Simian Collective (SimCo) 2025, Durham, NC, USA*]{.accent}

    **Sonal Kumar**, Annat Haber, Catrina Spruce, MARMO-AD Consortium, Diego Szczupak, Gregg Homanics, Afonso Silva, Stacey J. Sukoff Rizzo, Gregory W. Carter *\[August 2025\]*

-   **"Genetic associations of plasma biomarkers of neurodegeneration in a population of laboratory marmosets"**

    [*Alzheimer’s Association International Conference (AAIC) 2025, Toronto, Canada (Virtual presentation)*]{.accent}

    **Sonal Kumar**, Annat Haber, Catrina Spruce, MARMO-AD Consortium, Diego Szczupak, Gregg Homanics, Afonso Silva, Stacey J. Sukoff Rizzo, Gregory W. Carter *\[July 2025\]*

    <a href="https://alz-journals.onlinelibrary.wiley.com/doi/10.1002/alz70855_103724" class="btn btn-outline-primary">Abstract</a>
    
-   **"Genetic associations with plasma beta-amyloid peptides in a population of laboratory marmosets"**

    [*Alzheimer’s Disease Gordon Research Conference (GRC) 2025, Ventura, CA, USA*]{.accent}

    **Sonal Kumar**, Annat Haber, Catrina Spruce, MARMO-AD Consortium, Diego Szczupak, Gregg Homanics, Afonso Silva, Stacey J. Sukoff Rizzo, Gregory W. Carter *\[June 2025\]*


-   **"Identifying genetic contributors to Corpus Callosum Dysgenesis (CCD) in a population of laboratory marmosets"**

    [*Tufts GSBS Neuroscience Program Retreat 2025, Boston, MA, USA*]{.accent}

    **Sonal Kumar**, Annat Haber, Catrina Spruce, MARMO-AD Consortium, Diego Szczupak, Afonso Silva, Stacey J. Sukoff Rizzo, Gregory W. Carter *\[April 2025\]*

### 2024

-   **"Potentially heritable biomarkers of neurodegeneration in a marmoset model of Alzheimer’s disease"**

    [*Alzheimer’s Association International Conference (AAIC) 2024, Philadelphia, PA, USA*]{.accent}

    **Sonal Kumar**, Catrina Spruce, Annat Haber, Laura Schultz, Hasi Huhe, Takeshi Murai, Sang-Ho Choi, Stephanie Hachem, Yongshan Mou, Seung-Kwon Ha, Jung Eun Park, Lauren Bailey, Lauren Mongeau, Andrew DeSana, Brianne Stein, Lauren K Hayrynen Schaeffer, Gregg E Homanics, Afonso C Silva, Stacey J Sukoff Rizzo, Gregory W Carter *\[July 2024\]*

    <a href="https://doi.org/10.1002/alz.090952" class="btn btn-outline-primary">Abstract</a>

### 2022

-   **"Investigating the role of the noncanonical human small heat shock protein HSPB7 in Alzheimer’s disease"**

    [*IBAB Graduate Research Poster Symposium, IBAB, Bengaluru, India*]{.accent}

    **Sonal Kumar**, Bibha Choudhary *\[July 2022\]*

### 2020

-   **"Studying the effect of HSP16.2 overexpression on** $\beta$-amyloid protein aggregation in transgenic *Caenorhabditis elegans* CL2006"

    [*Present-Day Biology: Impact of Research at Molecular and Cellular Level. National conference, Ahmedabad, India. Presented under the theme ‘Diseases and Health’.*]{.accent}

    Pavan Matani, **Sonal Kumar**, Akshit Jain, Lavanya Lulla, Shital Doshi *\[January 2020\]*

### 2019

-   **"Biofortified Crops as a Possible Solution to Vitamin-A Deficiency in Developing Nations"**

    [*Present-Day Biology: A Bastion for Social and Sustainable Development. International conference, Ahmedabad, India. Presented under the theme ‘Interventions in Nutrition and Agriculture’.*]{.accent}

    **Sonal Kumar**, Payal Varandani, Lavanya Lulla *\[January 2019\]*
